export const DATA_NEVER = {
    VERY_HOT: {
        id: 'very_hot',
        label: 'Very Hot',
        icon: '🔥',
        desc: 'La température monte d\'un cran.',
        color: 'var(--very-hot)',
        gradient: 'var(--very-hot-gradient)',
        questions: [
            "Je n'ai jamais dormi nu avec quelqu'un",
            "Je n'ai jamais pris de douche à deux",
            "Je n'ai jamais fait l'amour le matin",
            "Je n'ai jamais fait l'amour sur un canapé",
            "Je n'ai jamais fait l'amour par terre",
            "Je n'ai jamais fait l'amour dans la cuisine",
            "Je n'ai jamais fait l'amour dans la salle de bain",
            "Je n'ai jamais fait l'amour devant un miroir",
            "Je n'ai jamais fait l'amour avec la lumière allumée",
            "Je n'ai jamais fait l'amour dans le noir complet",
            "Je n'ai jamais utilisé d'huile de massage",
            "Je n'ai jamais fait de strip-tease sérieux",
            "Je n'ai jamais reçu de lap dance",
            "Je n'ai jamais donné de lap dance",
            "Je n'ai jamais envoyé de nude",
            "Je n'ai jamais reçu de nude",
            "Je n'ai jamais fait de sexting",
            "Je n'ai jamais eu de conversation téléphonique coquine",
            "Je n'ai jamais fait l'amour sans préservatif (attention !)",
            "Je n'ai jamais pris la pilule du lendemain",
            "Je n'ai jamais acheté de test de grossesse",
            "Je n'ai jamais fait l'amour pendant les règles",
            "Je n'ai jamais fait l'amour plusieurs fois de suite",
            "Je n'ai jamais fait l'amour toute la nuit",
            "Je n'ai jamais été trop bruyant au lit",
            "Je n'ai jamais réveillé les voisins",
            "Je n'ai jamais cassé un lit",
            "Je n'ai jamais tombé du lit pendant l'acte",
            "Je n'ai jamais eu de crampe pendant l'acte",
            "Je n'ai jamais ri pendant l'acte",
            "Je n'ai jamais pleuré après l'acte",
            "Je n'ai jamais dormi tout de suite après",
            "Je n'ai jamais fait l'amour avec de la musique",
            "Je n'ai jamais fait de playlist pour faire l'amour",
            "Je n'ai jamais regardé de porno",
            "Je n'ai jamais regardé de porno en couple",
            "Je n'ai jamais imité une position du Kamasutra",
            "Je n'ai jamais essayé le 69",
            "Je n'ai jamais essayé la levrette",
            "Je n'ai jamais essayé l'andromaque",
            "Je n'ai jamais essayé le missionnaire",
            "Je n'ai jamais été attaché",
            "Je n'ai jamais attaché quelqu'un",
            "Je n'ai jamais utilisé de menottes",
            "Je n'ai jamais utilisé de foulard",
            "Je n'ai jamais utilisé de plume",
            "Je n'ai jamais utilisé de glaçon",
            "Je n'ai jamais utilisé de chantilly ou chocolat",
            "Je n'ai jamais mangé sur quelqu'un",
            "Je n'ai jamais mordu quelqu'un",
            "Je n'ai jamais été mordu",
            "Je n'ai jamais griffé quelqu'un",
            "Je n'ai jamais été griffé",
            "Je n'ai jamais donné de fessée",
            "Je n'ai jamais reçu de fessée",
            "Je n'ai jamais tiré les cheveux",
            "Je n'ai jamais aimé qu'on me tire les cheveux",
            "Je n'ai jamais dit des mots crus au lit",
            "Je n'ai jamais aimé qu'on me dise des mots crus",
            "Je n'ai jamais joué un rôle au lit",
            "Je n'ai jamais porté de déguisement au lit",
            "Je n'ai jamais fait l'amour dans un hôtel",
            "Je n'ai jamais fait l'amour chez des amis",
            "Je n'ai jamais fait l'amour chez mes parents",
            "Je n'ai jamais fait l'amour dans une tente",
            "Je n'ai jamais fait l'amour dans une voiture",
            "Je n'ai jamais fait l'amour sur une plage",
            "Je n'ai jamais fait l'amour dans l'eau",
            "Je n'ai jamais fait l'amour dans une piscine",
            "Je n'ai jamais fait l'amour dans un jacuzzi",
            "Je n'ai jamais fait l'amour dans un sauna",
            "Je n'ai jamais fait l'amour dans les bois",
            "Je n'ai jamais fait l'amour dans un champ",
            "Je n'ai jamais fait l'amour sur un balcon",
            "Je n'ai jamais fait l'amour dans un ascenseur",
            "Je n'ai jamais fait l'amour dans des escaliers",
            "Je n'ai jamais fait l'amour dans des toilettes",
            "Je n'ai jamais été surpris en train de faire l'amour",
            "Je n'ai jamais surpris mes parents",
            "Je n'ai jamais surpris des amis",
            "Je n'ai jamais entendu mes voisins faire l'amour",
            "Je n'ai jamais simulé un orgasme",
            "Je n'ai jamais eu d'orgasme multiple",
            "Je n'ai jamais eu de panne sexuelle",
            "Je n'ai jamais eu de fou rire nerveux au lit",
            "Je n'ai jamais appelé mon partenaire par le mauvais prénom au lit",
            "Je n'ai jamais pensé à quelqu'un d'autre pendant l'acte",
            "Je n'ai jamais fait l'amour pour me réconcilier",
            "Je n'ai jamais fait l'amour par pitié",
            "Je n'ai jamais fait l'amour par ennui",
            "Je n'ai jamais refusé de faire l'amour",
            "Je n'ai jamais initié un rapport",
            "Je n'ai jamais fait le premier pas pour aller au lit",
            "Je n'ai jamais dormi avec un ami avec bénéfices",
            "Je n'ai jamais eu de plan cul régulier",
            "Je n'ai jamais eu un coup d'un soir",
            "Je n'ai jamais recouché avec un ex",
            "Je n'ai jamais couché avec le même partenaire la même nuit",
            "Je n'ai jamais fait l'amour le jour de la Saint-Valentin"
        ]
    },
    SPICY: {
        id: 'spicy',
        label: 'Spicy',
        icon: '🌶️',
        desc: 'Expériences et fantasmes.',
        color: 'var(--spicy)',
        gradient: 'var(--spicy-gradient)',
        questions: [
            "Je n'ai jamais utilisé de sex toy",
            "Je n'ai jamais utilisé de sex toy à deux",
            "Je n'ai jamais offert de sex toy",
            "Je n'ai jamais été dans un sex shop",
            "Je n'ai jamais commandé sur un site coquin",
            "Je n'ai jamais regardé du hentai",
            "Je n'ai jamais lu de fanfiction érotique",
            "Je n'ai jamais lu 50 Nuances de Grey",
            "Je n'ai jamais fantasmé sur un personnage de fiction",
            "Je n'ai jamais fantasmé sur un prof",
            "Je n'ai jamais fantasmé sur un collègue",
            "Je n'ai jamais fantasmé sur le partenaire d'un ami",
            "Je n'ai jamais fantasmé sur un inconnu dans la rue",
            "Je n'ai jamais fantasmé sur quelqu'un du même sexe",
            "Je n'ai jamais fait de rêve érotique lucide",
            "Je n'ai jamais eu d'orgasme en dormant",
            "Je n'ai jamais pratiqué l'échangisme",
            "Je n'ai jamais pensé à l'échangisme",
            "Je n'ai jamais fait de plan à 3",
            "Je n'ai jamais voulu faire un plan à 3",
            "Je n'ai jamais regardé d'autres personnes faire l'amour",
            "Je n'ai jamais été regardé pendant l'acte",
            "Je n'ai jamais filmé mes ébats",
            "Je n'ai jamais pris de photos coquines de mon partenaire",
            "Je n'ai jamais laissé quelqu'un me prendre en photo nu",
            "Je n'ai jamais eu peur qu'une sextape fuite",
            "Je n'ai jamais fait l'amour avec un inconnu total",
            "Je n'ai jamais fait l'amour sans échanger un mot",
            "Je n'ai jamais fait l'amour les yeux bandés",
            "Je n'ai jamais fait l'amour avec les mains attachées",
            "Je n'ai jamais fait l'amour avec un baillon",
            "Je n'ai jamais pratiqué le BDSM soft",
            "Je n'ai jamais utilisé de fouet",
            "Je n'ai jamais utilisé de pince-tétons",
            "Je n'ai jamais utilisé de plug",
            "Je n'ai jamais utilisé de lubrifiant chauffant",
            "Je n'ai jamais utilisé de préservatif parfumé",
            "Je n'ai jamais fait l'amour devant la télé",
            "Je n'ai jamais fait l'amour pendant un film",
            "Je n'ai jamais fait l'amour en silence pour ne pas être entendu",
            "Je n'ai jamais fait l'amour très vite (quickie)",
            "Je n'ai jamais fait l'amour très lentement (tantra)",
            "Je n'ai jamais essayé le massage prostatique",
            "Je n'ai jamais essayé la sodomie",
            "Je n'ai jamais aimé la sodomie",
            "Je n'ai jamais fait de rimming",
            "Je n'ai jamais reçu de rimming",
            "Je n'ai jamais avalé",
            "Je n'ai jamais demandé à ce qu'on avale",
            "Je n'ai jamais reçu un facial",
            "Je n'ai jamais fait un facial",
            "Je n'ai jamais fait de 69 debout",
            "Je n'ai jamais porté de lingerie comestible",
            "Je n'ai jamais utilisé de peinture corporelle",
            "Je n'ai jamais fait l'amour devant une fenêtre ouverte",
            "Je n'ai jamais fait l'amour sur un balcon la nuit",
            "Je n'ai jamais fait l'amour dans une cabine d'essayage",
            "Je n'ai jamais fait l'amour dans des toilettes publiques",
            "Je n'ai jamais fait l'amour dans un avion (mile high club)",
            "Je n'ai jamais fait l'amour dans un train",
            "Je n'ai jamais fait l'amour dans un bus",
            "Je n'ai jamais fait l'amour dans un cinéma",
            "Je n'ai jamais fait l'amour dans un parc",
            "Je n'ai jamais fait l'amour dans un cimetière",
            "Je n'ai jamais fait l'amour dans une église",
            "Je n'ai jamais fait l'amour au travail",
            "Je n'ai jamais fait l'amour à l'école/fac",
            "Je n'ai jamais fait l'amour dans une bibliothèque",
            "Je n'ai jamais fait l'amour dans un musée",
            "Je n'ai jamais fait l'amour dans une piscine municipale",
            "Je n'ai jamais fait l'amour dans la mer",
            "Je n'ai jamais fait l'amour sur un bateau",
            "Je n'ai jamais fait l'amour sous la tente en festival",
            "Je n'ai jamais fait l'amour dans un sac de couchage",
            "Je n'ai jamais fait l'amour sur une machine à laver",
            "Je n'ai jamais fait l'amour sur une table de cuisine",
            "Je n'ai jamais fait l'amour sur un bureau",
            "Je n'ai jamais fait l'amour sur un piano",
            "Je n'ai jamais fait l'amour sur un billard",
            "Je n'ai jamais fait l'amour devant une cheminée",
            "Je n'ai jamais fait l'amour sur une peau de bête",
            "Je n'ai jamais fait l'amour avec des talons",
            "Je n'ai jamais fait l'amour avec des chaussettes",
            "Je n'ai jamais fait l'amour tout habillé",
            "Je n'ai jamais déchiré les vêtements de quelqu'un",
            "Je n'ai jamais eu mes vêtements déchirés",
            "Je n'ai jamais joué au docteur",
            "Je n'ai jamais joué au professeur/élève",
            "Je n'ai jamais joué au policier/voleur",
            "Je n'ai jamais joué au patron/secrétaire",
            "Je n'ai jamais utilisé de cravate pour attacher",
            "Je n'ai jamais utilisé de ceinture",
            "Je n'ai jamais donné de fessée avec un objet",
            "Je n'ai jamais reçu de fessée avec un objet",
            "Je n'ai jamais aimé la douleur",
            "Je n'ai jamais aimé infliger la douleur",
            "Je n'ai jamais eu de marque de dents",
            "Je n'ai jamais laissé de marque de dents",
            "Je n'ai jamais eu de griffures dans le dos",
            "Je n'ai jamais griffé le dos de quelqu'un"
        ]
    },
    DANGEROUS: {
        id: 'dangerous',
        label: 'Dangerous',
        icon: '☢️',
        desc: 'Tabous, risques et interdits.',
        color: 'var(--dangerous)',
        gradient: 'var(--dangerous-gradient)',
        questions: [
            "Je n'ai jamais couché avec le frère/sœur d'un ami",
            "Je n'ai jamais couché avec l'ex d'un ami",
            "Je n'ai jamais couché avec le partenaire d'un ami",
            "Je n'ai jamais brisé un couple",
            "Je n'ai jamais été la maîtresse / l'amant",
            "Je n'ai jamais eu deux relations en même temps",
            "Je n'ai jamais menti sur mon prénom pour un coup d'un soir",
            "Je n'ai jamais donné un faux numéro après avoir couché",
            "Je n'ai jamais volé quelque chose chez un coup d'un soir",
            "Je n'ai jamais fouillé les tiroirs d'un coup d'un soir",
            "Je n'ai jamais couché pour obtenir quelque chose",
            "Je n'ai jamais couché pour une promotion",
            "Je n'ai jamais couché pour de l'argent",
            "Je n'ai jamais payé pour du sexe",
            "Je n'ai jamais été dans un club échangiste",
            "Je n'ai jamais été dans un club libertin",
            "Je n'ai jamais participé à une orgie",
            "Je n'ai jamais fait l'amour avec plus de 2 personnes en même temps",
            "Je n'ai jamais fait l'amour avec des jumeaux/jumelles",
            "Je n'ai jamais fait l'amour avec un membre de ma belle-famille",
            "Je n'ai jamais eu de fantasme incestueux",
            "Je n'ai jamais fait l'amour sans protection avec un inconnu",
            "Je n'ai jamais menti sur ma santé sexuelle",
            "Je n'ai jamais transmis une IST",
            "Je n'ai jamais attrapé une IST",
            "Je n'ai jamais eu peur d'avoir une IST",
            "Je n'ai jamais fait de test de paternité",
            "Je n'ai jamais douté de la paternité d'un enfant",
            "Je n'ai jamais avorté (ou partenaire)",
            "Je n'ai jamais fait l'amour dans un lieu de culte",
            "Je n'ai jamais fait l'amour dans un cimetière la nuit",
            "Je n'ai jamais fait l'amour dans une école",
            "Je n'ai jamais fait l'amour dans un hôpital",
            "Je n'ai jamais fait l'amour dans un commissariat",
            "Je n'ai jamais fait l'amour dans une prison",
            "Je n'ai jamais fait l'amour avec un uniforme",
            "Je n'ai jamais fait l'amour avec une personne mariée",
            "Je n'ai jamais fait l'amour avec une personne fiancée",
            "Je n'ai jamais fait l'amour la veille de mon mariage avec quelqu'un d'autre",
            "Je n'ai jamais annulé un mariage",
            "Je n'ai jamais été laissé devant l'autel",
            "Je n'ai jamais divorcé",
            "Je n'ai jamais fait l'amour avec mon avocat",
            "Je n'ai jamais fait l'amour avec mon médecin",
            "Je n'ai jamais fait l'amour avec mon psy",
            "Je n'ai jamais fait l'amour avec mon prof",
            "Je n'ai jamais fait l'amour avec mon élève (majeur)",
            "Je n'ai jamais fait l'amour avec mon patron",
            "Je n'ai jamais fait l'amour avec mon employé",
            "Je n'ai jamais fait l'amour avec le parent d'un ami",
            "Je n'ai jamais fait l'amour avec l'enfant (majeur) d'un ami",
            "Je n'ai jamais fait l'amour avec un voisin marié",
            "Je n'ai jamais été surpris par la police",
            "Je n'ai jamais eu une amende pour exhibitionnisme",
            "Je n'ai jamais marché nu dans la rue",
            "Je n'ai jamais conduit nu",
            "Je n'ai jamais fait l'amour en conduisant",
            "Je n'ai jamais eu d'accident à cause du sexe",
            "Je n'ai jamais cassé un objet de valeur pendant le sexe",
            "Je n'ai jamais blessé quelqu'un pendant le sexe",
            "Je n'ai jamais été blessé et fini aux urgences",
            "Je n'ai jamais coincé un objet en moi",
            "Je n'ai jamais dû appeler les pompiers pour un problème sexuel",
            "Je n'ai jamais pris de drogue pour le sexe",
            "Je n'ai jamais été trop ivre pour performer",
            "Je n'ai jamais vomi pendant l'acte",
            "Je n'ai jamais dormi pendant l'acte",
            "Je n'ai jamais oublié le prénom pendant l'acte",
            "Je n'ai jamais appelé maman/papa pendant l'acte",
            "Je n'ai jamais pleuré de tristesse pendant l'acte",
            "Je n'ai jamais eu une crise de panique pendant l'acte",
            "Je n'ai jamais fait l'amour avec quelqu'un que je détestais",
            "Je n'ai jamais fait l'amour pour me venger",
            "Je n'ai jamais fait l'amour pour rendre service",
            "Je n'ai jamais fait l'amour par pari",
            "Je n'ai jamais perdu un pari sexuel",
            "Je n'ai jamais filmé quelqu'un à son insu (illégal !)",
            "Je n'ai jamais diffusé des photos intimes (revenge porn)",
            "Je n'ai jamais été victime de revenge porn",
            "Je n'ai jamais fait de chantage sexuel",
            "Je n'ai jamais subi de chantage sexuel",
            "Je n'ai jamais eu de relation toxique",
            "Je n'ai jamais été violent physiquement",
            "Je n'ai jamais subi de violence physique",
            "Je n'ai jamais harcelé quelqu'un",
            "Je n'ai jamais été harcelé",
            "Je n'ai jamais eu d'ordonnance d'éloignement",
            "Je n'ai jamais espionné quelqu'un avec un logiciel",
            "Je n'ai jamais mis un traceur GPS",
            "Je n'ai jamais lu le journal intime de quelqu'un",
            "Je n'ai jamais écouté aux portes",
            "Je n'ai jamais regardé par la serrure",
            "Je n'ai jamais utilisé de jumelles pour espionner",
            "Je n'ai jamais volé un sous-vêtement",
            "Je n'ai jamais senti un sous-vêtement sale",
            "Je n'ai jamais acheté un sous-vêtement porté",
            "Je n'ai jamais vendu un sous-vêtement porté",
            "Je n'ai jamais fait l'amour avec un animal (non, jamais !)",
            "Je n'ai jamais eu de fantasme zoophile (beurk)",
            "Je n'ai jamais fait l'amour avec un cadavre (nécrophilie, non !)"
        ]
    }
};

export const QUESTIONS_WHO = [
    { text: "Qui pourrait faire toutes les positions du Kamasutra en une nuit ?", tags: ['sexe'], base: 7 },
    { text: "Qui pourrait coucher avec le/la partenaire de son meilleur ami ?", tags: ['sexe', 'honte'], base: 8 },
    { text: "Qui pourrait finir en prison après une soirée trop arrosée ?", tags: ['alcool', 'illegal'], base: 7 },
    { text: "Qui pourrait essayer toutes les drogues au moins une fois ?", tags: ['drogue'], base: 8 },
    { text: "Qui pourrait avoir une sextape qui fuite sur internet ?", tags: ['sexe', 'honte'], base: 9 },
    { text: "Qui pourrait se marier à Vegas avec un inconnu ?", tags: ['alcool'], base: 6 },
    { text: "Qui pourrait devenir une star du porno ?", tags: ['sexe'], base: 7 },
    { text: "Qui pourrait ne pas se laver pendant une semaine ?", tags: ['salete'], base: 5 },
    { text: "Qui pourrait manger quelque chose tombé dans les toilettes pour 100€ ?", tags: ['salete', 'honte'], base: 8 },
    { text: "Qui pourrait coucher pour une promotion ?", tags: ['sexe'], base: 7 },
    { text: "Qui pourrait avoir le plus de partenaires sexuels dans sa vie ?", tags: ['sexe'], base: 5 },
    { text: "Qui pourrait simuler un orgasme à chaque fois ?", tags: ['sexe'], base: 6 },
    { text: "Qui pourrait oublier le prénom de son partenaire pendant l'acte ?", tags: ['sexe', 'honte'], base: 6 },
    { text: "Qui pourrait vomir sur son partenaire pendant l'amour ?", tags: ['sexe', 'salete', 'alcool'], base: 9 },
    { text: "Qui pourrait avoir une relation secrète avec un membre de sa famille (cousin/e) ?", tags: ['sexe', 'honte'], base: 10 },
    { text: "Qui pourrait se faire tatouer le nom de son ex ?", tags: ['honte'], base: 6 },
    { text: "Qui pourrait pleurer après avoir fait l'amour ?", tags: ['sexe'], base: 5 },
    { text: "Qui pourrait s'endormir pendant l'acte ?", tags: ['sexe'], base: 6 },
    { text: "Qui pourrait avoir un compte OnlyFans ?", tags: ['sexe'], base: 5 },
    { text: "Qui pourrait payer pour du sexe ?", tags: ['sexe'], base: 6 },
    { text: "Qui pourrait être arrêté pour exhibitionnisme ?", tags: ['sexe', 'illegal'], base: 8 },
    { text: "Qui pourrait faire l'amour dans un lieu public bondé ?", tags: ['sexe', 'illegal'], base: 9 },
    { text: "Qui pourrait avoir le plus de jouets sexuels ?", tags: ['sexe'], base: 4 },
    { text: "Qui pourrait participer à une orgie ?", tags: ['sexe'], base: 8 },
    { text: "Qui pourrait être échangiste ?", tags: ['sexe'], base: 7 },
    { text: "Qui pourrait tomber amoureux d'un strip-teaseur / strip-teaseuse ?", tags: ['sexe'], base: 5 },
    { text: "Qui pourrait envoyer un nude à son patron par erreur ?", tags: ['sexe', 'honte'], base: 9 },
    { text: "Qui pourrait se faire prendre en train de se masturber ?", tags: ['sexe', 'honte'], base: 7 },
    { text: "Qui pourrait avoir une MST sans le savoir ?", tags: ['sexe', 'salete'], base: 7 },
    { text: "Qui pourrait ne pas changer de sous-vêtements pendant 3 jours ?", tags: ['salete'], base: 6 },
    { text: "Qui pourrait boire l'eau des toilettes ?", tags: ['salete'], base: 9 },
    { text: "Qui pourrait manger ses crottes de nez en public ?", tags: ['salete', 'honte'], base: 7 },
    { text: "Qui pourrait péter bruyamment lors d'un premier rendez-vous ?", tags: ['honte', 'salete'], base: 8 },
    { text: "Qui pourrait conduire ivre ?", tags: ['alcool', 'illegal'], base: 9 },
    { text: "Qui pourrait se battre dans un bar ?", tags: ['alcool', 'illegal'], base: 7 },
    { text: "Qui pourrait voler dans un magasin ?", tags: ['illegal'], base: 6 },
    { text: "Qui pourrait vendre de la drogue ?", tags: ['drogue', 'illegal'], base: 9 },
    { text: "Qui pourrait fumer un joint avec ses parents ?", tags: ['drogue'], base: 6 },
    { text: "Qui pourrait arriver au travail encore ivre de la veille ?", tags: ['alcool'], base: 7 },
    { text: "Qui pourrait dépenser tout son salaire en une soirée ?", tags: ['alcool'], base: 6 },
    { text: "Qui pourrait se réveiller dans un autre pays après une soirée ?", tags: ['alcool'], base: 8 },
    { text: "Qui pourrait embrasser le plus de personnes en une soirée ?", tags: ['sexe'], base: 5 },
    { text: "Qui pourrait sortir avec l'ex de son meilleur ami ?", tags: ['honte'], base: 8 },
    { text: "Qui pourrait mentir sur sa vie entière pour séduire ?", tags: ['honte'], base: 7 },
    { text: "Qui pourrait tromper son partenaire et ne jamais le dire ?", tags: ['sexe', 'honte'], base: 9 },
    { text: "Qui pourrait fouiller dans le téléphone de son partenaire ?", tags: ['honte'], base: 5 },
    { text: "Qui pourrait être le plus jaloux maladif ?", tags: ['honte'], base: 5 },
    { text: "Qui pourrait faire une scène de ménage en public ?", tags: ['honte'], base: 6 },
    { text: "Qui pourrait stalker son ex pendant des années ?", tags: ['honte'], base: 7 },
    { text: "Qui pourrait avoir le fétichisme le plus bizarre ?", tags: ['sexe'], base: 6 }
,
    { text: "Qui pourrait se faire pipi dessus de rire ?", tags: ["honte", "fun"], base: 6 },
    { text: "Qui pourrait vomir dans un Uber ?", tags: ["alcool", "salete", "honte"], base: 8 },
    { text: "Qui pourrait s'endormir en boîte de nuit ?", tags: ["alcool", "fatigue"], base: 5 },
    { text: "Qui pourrait perdre ses chaussures en soirée ?", tags: ["alcool", "maladresse"], base: 6 },
    { text: "Qui pourrait se réveiller avec un inconnu ?", tags: ["sexe", "alcool", "surprise"], base: 7 },
    { text: "Qui pourrait envoyer un nude par Airdrop dans le métro ?", tags: ["sexe", "honte", "tech"], base: 9 },
    { text: "Qui pourrait liker une photo de son ex datant de 2015 par erreur ?", tags: ["honte", "social"], base: 7 },
    { text: "Qui pourrait se faire griller en train de stalker ?", tags: ["honte", "social"], base: 6 },
    { text: "Qui pourrait avoir un faux compte pour espionner ?", tags: ["social", "secret"], base: 5 },
    { text: "Qui pourrait manger par terre ?", tags: ["salete", "nourriture"], base: 4 },
    { text: "Qui pourrait ne pas se brosser les dents le soir ?", tags: ["salete"], base: 3 },
    { text: "Qui pourrait sentir ses chaussettes pour voir si elles sont propres ?", tags: ["salete"], base: 4 },
    { text: "Qui pourrait remettre un caleçon sale ?", tags: ["salete"], base: 5 },
    { text: "Qui pourrait pisser sous la douche ?", tags: ["salete", "ecologie"], base: 2 },
    { text: "Qui pourrait pisser dans un lavabo ?", tags: ["salete", "honte"], base: 6 },
    { text: "Qui pourrait voler un verre dans un bar ?", tags: ["illegal", "alcool"], base: 4 },
    { text: "Qui pourrait partir sans payer au resto ?", tags: ["illegal", "radin"], base: 8 },
    { text: "Qui pourrait resquiller dans le métro ?", tags: ["illegal"], base: 5 },
    { text: "Qui pourrait se battre pour une place de parking ?", tags: ["colere", "voiture"], base: 6 },
    { text: "Qui pourrait insulter un agent de police ?", tags: ["illegal", "colere", "stupide"], base: 9 },
    { text: "Qui pourrait finir en garde à vue pour une bêtise ?", tags: ["illegal", "stupide"], base: 8 },
    { text: "Qui pourrait se faire tatouer sur un coup de tête ?", tags: ["style", "folie"], base: 7 },
    { text: "Qui pourrait se raser les sourcils ?", tags: ["style", "bizarre"], base: 6 },
    { text: "Qui pourrait se teindre les cheveux en vert ?", tags: ["style", "folie"], base: 5 },
    { text: "Qui pourrait porter des Crocs au premier rendez-vous ?", tags: ["style", "honte"], base: 7 },
    { text: "Qui pourrait mettre des chaussettes avec des sandales ?", tags: ["style", "beauf"], base: 4 },
    { text: "Qui pourrait avoir un fond d'écran de lui-même ?", tags: ["ego"], base: 5 },
    { text: "Qui pourrait googler son propre nom ?", tags: ["ego"], base: 3 },
    { text: "Qui pourrait rire à sa propre blague ?", tags: ["ego", "humour"], base: 2 },
    { text: "Qui pourrait parler à son chat/chien comme à un humain ?", tags: ["mignon", "bizarre"], base: 3 },
    { text: "Qui pourrait croire aux fantômes ?", tags: ["croyance"], base: 4 },
    { text: "Qui pourrait avoir peur du noir ?", tags: ["peur"], base: 3 },
    { text: "Qui pourrait dormir avec une veilleuse ?", tags: ["peur", "mignon"], base: 3 },
    { text: "Qui pourrait sucer son pouce en secret ?", tags: ["honte", "enfantin"], base: 6 },
    { text: "Qui pourrait manger ses crottes de nez ?", tags: ["salete", "degout"], base: 8 },
    { text: "Qui pourrait se ronger les ongles de pieds ?", tags: ["salete", "bizarre"], base: 7 },
    { text: "Qui pourrait péter dans un ascenseur et accuser quelqu'un d'autre ?", tags: ["salete", "traitrise"], base: 6 },
    { text: "Qui pourrait boucher les toilettes chez ses beaux-parents ?", tags: ["honte", "salete"], base: 9 },
    { text: "Qui pourrait casser un objet de valeur chez des amis ?", tags: ["maladresse", "honte"], base: 7 },
    { text: "Qui pourrait renverser son verre sur la mariée ?", tags: ["maladresse", "honte"], base: 10 },
    { text: "Qui pourrait demander quelqu'un en mariage au McDo ?", tags: ["amour", "beauf"], base: 8 },
    { text: "Qui pourrait oublier l'anniversaire de son partenaire ?", tags: ["amour", "memoire"], base: 7 },
    { text: "Qui pourrait offrir un cadeau pourri à Noël ?", tags: ["radin", "cadeau"], base: 5 },
    { text: "Qui pourrait revendre ses cadeaux de Noël ?", tags: ["radin", "commerce"], base: 6 },
    { text: "Qui pourrait manger la part de gâteau de quelqu'un d'autre ?", tags: ["gourmandise", "ego"], base: 4 },
    { text: "Qui pourrait finir le Nutella et remettre le pot vide dans le placard ?", tags: ["traitrise", "gourmandise"], base: 5 },
    { text: "Qui pourrait boire du lait à la bouteille ?", tags: ["salete"], base: 3 },
    { text: "Qui pourrait manger froid une pizza de la veille ?", tags: ["gourmandise"], base: 2 },
    { text: "Qui pourrait manger des pâtes au ketchup ?", tags: ["cuisine"], base: 3 },
    { text: "Qui pourrait mettre de l'ananas sur sa pizza ?", tags: ["cuisine", "debat"], base: 4 },
    { text: "Qui pourrait tremper ses frites dans son milkshake ?", tags: ["cuisine", "bizarre"], base: 5 },
    { text: "Qui pourrait manger un insecte pour 50€ ?", tags: ["degout", "argent"], base: 6 },
    { text: "Qui pourrait lécher le sol pour 100€ ?", tags: ["salete", "argent"], base: 8 },
    { text: "Qui pourrait courir nu dans la rue pour 500€ ?", tags: ["illegal", "argent", "nudite"], base: 9 },
    { text: "Qui pourrait se raser la tête pour 1000€ ?", tags: ["style", "argent"], base: 7 },
    { text: "Qui pourrait arrêter son téléphone pendant 1 mois ?", tags: ["tech", "defi"], base: 8 },
    { text: "Qui pourrait vivre sans internet pendant 1 semaine ?", tags: ["tech", "defi"], base: 6 },
    { text: "Qui pourrait participer à Koh-Lanta ?", tags: ["aventure", "tele"], base: 5 },
    { text: "Qui pourrait gagner les Anges de la télé-réalité ?", tags: ["tele", "clash"], base: 6 },
    { text: "Qui pourrait devenir influenceur ?", tags: ["social", "carriere"], base: 4 },
    { text: "Qui pourrait acheter des followers ?", tags: ["social", "honte"], base: 7 },
    { text: "Qui pourrait retoucher toutes ses photos ?", tags: ["social", "ego"], base: 5 },
    { text: "Qui pourrait utiliser Tinder juste pour l'ego ?", tags: ["amour", "ego"], base: 4 },
    { text: "Qui pourrait avoir plusieurs plans cul en même temps ?", tags: ["sexe"], base: 6 },
    { text: "Qui pourrait confondre les prénoms de ses conquêtes ?", tags: ["sexe", "honte"], base: 8 },
    { text: "Qui pourrait coucher le premier soir ?", tags: ["sexe"], base: 4 },
    { text: "Qui pourrait ne jamais coucher le premier soir ?", tags: ["sexe", "principe"], base: 4 },
    { text: "Qui pourrait attendre le mariage ?", tags: ["sexe", "religion"], base: 6 },
    { text: "Qui pourrait avoir le plus d'enfants ?", tags: ["famille"], base: 3 },
    { text: "Qui pourrait ne jamais vouloir d'enfants ?", tags: ["famille"], base: 3 },
    { text: "Qui pourrait finir vieille fille / vieux garçon ?", tags: ["amour", "solitude"], base: 5 },
    { text: "Qui pourrait vivre chez ses parents jusqu'à 40 ans ?", tags: ["famille", "tanguy"], base: 6 },
    { text: "Qui pourrait devenir millionnaire ?", tags: ["argent", "succes"], base: 3 },
    { text: "Qui pourrait tout dépenser au casino ?", tags: ["argent", "jeu"], base: 7 },
    { text: "Qui pourrait se faire arnaquer en ligne ?", tags: ["argent", "naif"], base: 6 },
    { text: "Qui pourrait donner son code de carte bleue ?", tags: ["argent", "naif"], base: 8 },
    { text: "Qui pourrait perdre ses clés tous les jours ?", tags: ["memoire"], base: 4 },
    { text: "Qui pourrait oublier où il a garé sa voiture ?", tags: ["memoire"], base: 4 },
    { text: "Qui pourrait rater son avion ?", tags: ["retard"], base: 6 },
    { text: "Qui pourrait se tromper de train ?", tags: ["orientation"], base: 5 },
    { text: "Qui pourrait s'endormir au cinéma ?", tags: ["fatigue"], base: 3 },
    { text: "Qui pourrait parler fort au téléphone dans le train ?", tags: ["impolitesse"], base: 5 },
    { text: "Qui pourrait écouter de la musique sans écouteurs en public ?", tags: ["impolitesse"], base: 6 },
    { text: "Qui pourrait doubler tout le monde dans la file d'attente ?", tags: ["impolitesse"], base: 7 },
    { text: "Qui pourrait ne pas laisser sa place à une mamie ?", tags: ["impolitesse"], base: 8 },
    { text: "Qui pourrait aider une mamie à traverser ?", tags: ["gentillesse"], base: 2 },
    { text: "Qui pourrait sauver un chaton dans un arbre ?", tags: ["gentillesse", "courage"], base: 3 },
    { text: "Qui pourrait pleurer devant un film romantique ?", tags: ["emotion"], base: 3 },
    { text: "Qui pourrait avoir peur devant un film d'horreur ?", tags: ["peur"], base: 3 },
    { text: "Qui pourrait crier dans un manège ?", tags: ["peur", "fun"], base: 3 },
    { text: "Qui pourrait vomir dans un manège ?", tags: ["malade", "honte"], base: 6 },
    { text: "Qui pourrait avoir le vertige sur un escabeau ?", tags: ["peur"], base: 4 },
    { text: "Qui pourrait ne pas savoir changer une ampoule ?", tags: ["bricolage"], base: 4 },
    { text: "Qui pourrait ne pas savoir faire cuire des pâtes ?", tags: ["cuisine"], base: 5 },
    { text: "Qui pourrait faire brûler de l'eau ?", tags: ["cuisine", "stupide"], base: 6 },
    { text: "Qui pourrait appeler sa mère pour un rien ?", tags: ["famille"], base: 4 },
    { text: "Qui pourrait être un "fils à maman" / "fille à papa" ?", tags: ["famille"], base: 5 },
    { text: "Qui pourrait être le chouchou du prof ?", tags: ["ecole"], base: 4 },
    { text: "Qui pourrait tricher à un examen ?", tags: ["ecole", "triche"], base: 6 },
    { text: "Qui pourrait copier sur son voisin ?", tags: ["ecole", "triche"], base: 5 },
    { text: "Qui pourrait s'endormir en cours/réunion ?", tags: ["ecole", "travail", "fatigue"], base: 5 },
    { text: "Qui pourrait arriver en retard à son propre mariage ?", tags: ["retard", "mariage"], base: 8 },
    { text: "Qui pourrait dire le mauvais prénom à l'autel ?", tags: ["honte", "mariage"], base: 10 },
    { text: "Qui pourrait tomber amoureux d'un personnage de fiction ?", tags: ["amour", "imaginaire"], base: 4 },
    { text: "Qui pourrait parler aux plantes ?", tags: ["nature", "bizarre"], base: 3 },
    { text: "Qui pourrait faire un câlin à un arbre ?", tags: ["nature", "hippie"], base: 4 },
    { text: "Qui pourrait devenir vegan ?", tags: ["alimentation"], base: 3 },
    { text: "Qui pourrait manger de la viande crue ?", tags: ["alimentation", "bizarre"], base: 5 },
    { text: "Qui pourrait faire un jeûne de 3 jours ?", tags: ["sante", "defi"], base: 5 },
    { text: "Qui pourrait courir un marathon ?", tags: ["sport"], base: 4 },
    { text: "Qui pourrait abandonner le sport après 1 semaine ?", tags: ["sport", "flemme"], base: 3 },
    { text: "Qui pourrait prendre l'ascenseur pour 1 étage ?", tags: ["flemme"], base: 3 },
    { text: "Qui pourrait commander Uber Eats 3 fois par jour ?", tags: ["flemme", "argent"], base: 6 },
    { text: "Qui pourrait ne pas savoir faire une machine à laver ?", tags: ["menage"], base: 5 },
    { text: "Qui pourrait mélanger le blanc et les couleurs ?", tags: ["menage", "catastrophe"], base: 4 },
    { text: "Qui pourrait rétrécir un pull en laine ?", tags: ["menage", "catastrophe"], base: 4 },
    { text: "Qui pourrait casser son téléphone en le faisant tomber dans les toilettes ?", tags: ["maladresse", "honte"], base: 7 },
    { text: "Qui pourrait marcher dans une crotte de chien ?", tags: ["malchance"], base: 3 },
    { text: "Qui pourrait se prendre une porte vitrée ?", tags: ["maladresse", "douleur"], base: 5 },
    { text: "Qui pourrait tomber dans les escaliers ?", tags: ["maladresse"], base: 4 },
    { text: "Qui pourrait s'étouffer avec sa propre salive ?", tags: ["maladresse"], base: 3 },
    { text: "Qui pourrait rire au mauvais moment ?", tags: ["honte", "social"], base: 5 },
    { text: "Qui pourrait faire une blague raciste sans faire exprès ?", tags: ["honte", "social"], base: 9 },
    { text: "Qui pourrait offenser tout le monde en soirée ?", tags: ["social", "conflit"], base: 7 },
    { text: "Qui pourrait être le plus gros fêtard ?", tags: ["fete"], base: 3 },
    { text: "Qui pourrait être le premier couché en soirée ?", tags: ["fete", "fatigue"], base: 4 },
    { text: "Qui pourrait vomir avant minuit ?", tags: ["fete", "alcool"], base: 6 },
    { text: "Qui pourrait danser sur la table ?", tags: ["fete", "danse"], base: 5 },
    { text: "Qui pourrait faire un strip-tease en soirée ?", tags: ["fete", "sexe"], base: 7 },
    { text: "Qui pourrait embrasser n'importe qui ?", tags: ["fete", "amour"], base: 6 },
    { text: "Qui pourrait perdre son téléphone en soirée ?", tags: ["fete", "perte"], base: 5 },
    { text: "Qui pourrait rentrer à pied parce qu'il a plus de batterie ?", tags: ["galere"], base: 4 },
    { text: "Qui pourrait dormir dans la rue ?", tags: ["galere", "alcool"], base: 8 },
    { text: "Qui pourrait se faire voler ses chaussures ?", tags: ["galere", "vol"], base: 6 },
    { text: "Qui pourrait se faire arrêter par la police ?", tags: ["illegal"], base: 7 },
    { text: "Qui pourrait finir aux urgences ?", tags: ["sante", "accident"], base: 6 },
    { text: "Qui pourrait avoir une idée de génie bourré ?", tags: ["alcool", "idee"], base: 4 },
    { text: "Qui pourrait créer une start-up ?", tags: ["travail", "succes"], base: 3 },
    { text: "Qui pourrait tout plaquer pour élever des chèvres ?", tags: ["vie", "nature"], base: 5 },
    { text: "Qui pourrait faire le tour du monde ?", tags: ["voyage"], base: 3 },
    { text: "Qui pourrait partir vivre sur Mars ?", tags: ["espace", "futur"], base: 6 },
    { text: "Qui pourrait être un alien déguisé ?", tags: ["bizarre"], base: 5 },
    { text: "Qui pourrait être un agent secret ?", tags: ["secret"], base: 4 },
    { text: "Qui pourrait avoir une double vie ?", tags: ["secret", "mensonge"], base: 8 },
    { text: "Qui pourrait être un tueur en série ?", tags: ["dark", "crime"], base: 10 },
];
